version: '3.8'
services:
  mysql:
    image: 'mysql:8.1.0'
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: erp
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - "3307:3306"
    restart: always

volumes:
  mysql-data: